create table snippets (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null unique,
  description text,
  code text not null,
  language text default 'text'
);

alter table snippets disable row level security;